# Generated by Django 5.2.4 on 2025-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=4, verbose_name='کد')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'کد OTP',
                'verbose_name_plural': 'کد های OTP',
            },
        ),
    ]
