# Generated by Django 5.2.4 on 2025-08-19 06:55

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام برچسب')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='course.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('short_description', models.TextField(max_length=500, verbose_name='توضیح کوتاه')),
                ('description', tinymce.models.HTMLField(verbose_name='توضیحات کامل')),
                ('requirements', tinymce.models.HTMLField(blank=True, verbose_name='پیش\u200cنیازها')),
                ('what_you_learn', tinymce.models.HTMLField(blank=True, verbose_name='آنچه یاد خواهید گرفت')),
                ('thumbnail', models.ImageField(upload_to='courses/thumbnails/', verbose_name='تصویر شاخص')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='courses/banners/', verbose_name='بنر دوره')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('expert', 'تخصصی')], default='beginner', max_length=20, verbose_name='سطح دوره')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی'), ('ar', 'عربی')], default='fa', max_length=5, verbose_name='زبان دوره')),
                ('duration', models.PositiveIntegerField(help_text='مدت زمان به دقیقه', verbose_name='مدت زمان (دقیقه)')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت با تخفیف (تومان)')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='course.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دوره آموزشی',
                'verbose_name_plural': 'دوره\u200cهای آموزشی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='پیشرفت (درصد)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='گواهی صادر شده')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, through='course.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='دانشجویان'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=50, unique=True, verbose_name='شماره گواهی')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('is_valid', models.BooleanField(default=True, verbose_name='معتبر')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.enrollment', verbose_name='ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'گواهی\u200cنامه',
                'verbose_name_plural': 'گواهی\u200cنامه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', tinymce.models.HTMLField(blank=True, verbose_name='بیوگرافی')),
                ('specialization', models.CharField(max_length=200, verbose_name='تخصص')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سال\u200cهای تجربه')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='تصویر پروفایل')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('github', models.URLField(blank=True, verbose_name='گیت\u200cهاب')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'مدرسین',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.instructor', verbose_name='مدرس'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بخش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('is_free', models.BooleanField(default=False, verbose_name='بخش رایگان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان درس')),
                ('slug', models.SlugField(max_length=200, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='محتوا')),
                ('lesson_type', models.CharField(choices=[('video', 'ویدیو'), ('text', 'متن'), ('quiz', 'آزمون'), ('assignment', 'تکلیف'), ('file', 'فایل')], default='video', max_length=20, verbose_name='نوع درس')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='فایل ویدیو')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدیو')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='courses/attachments/', verbose_name='ضمیمه')),
                ('duration', models.PositiveIntegerField(default=0, help_text='مدت زمان به ثانیه', verbose_name='مدت زمان (ثانیه)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('is_free', models.BooleanField(default=False, verbose_name='درس رایگان')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.section', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='course.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='مدت تماشا (ثانیه)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='course.enrollment', verbose_name='ثبت\u200cنام')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'پیشرفت درس',
                'verbose_name_plural': 'پیشرفت درس\u200cها',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نظر')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='course.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
