# Generated by Django 5.2.4 on 2025-09-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_review_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(help_text='مدت زمان به ساعت', verbose_name='مدت زمان (ساعت)'),
        ),
    ]
