# Generated by Django 5.2.4 on 2025-09-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_discount_percent_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)'),
        ),
    ]
