# Generated by Django 5.2.4 on 2025-09-11 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_course_discount_percent_alter_course_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (ریال)')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد Authority')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('successful', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment', verbose_name='پرداخت مرتبط')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام در دوره',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها در دوره\u200cها',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
