# Generated by Django 5.2.4 on 2025-08-23 06:21

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان صفحه که در هدر و عنوان مرورگر نمایش داده می\u200cشود', max_length=200, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, help_text='آدرس صفحه در URL (به صورت خودکار از عنوان ایجاد می\u200cشود)', max_length=200, unique=True, verbose_name='اسلاگ')),
                ('content', tinymce.models.HTMLField(help_text='محتوا اصلی صفحه که با ویرایشگر TinyMCE قابل ویرایش است', verbose_name='محتوا')),
                ('meta_title', models.CharField(blank=True, help_text='عنوانی که در نتایج جستجو نمایش داده می\u200cشود (حداکثر 60 کاراکتر)', max_length=60, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, help_text='توضیح مختصر برای نمایش در نتایج جستجو (حداکثر 160 کاراکتر)', max_length=160, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, help_text='کلمات کلیدی مرتبط با صفحه (با کاما جدا شوند)', max_length=200, verbose_name='کلمات کلیدی متا')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('hidden', 'مخفی')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('show_in_navigation', models.BooleanField(default=False, help_text='آیا این صفحه در منوی اصلی سایت نمایش داده شود؟', verbose_name='نمایش در منو')),
                ('navigation_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش صفحه در منو (اعداد کمتر اولویت بالاتری دارند)', verbose_name='ترتیب در منو')),
                ('featured_image', models.ImageField(blank=True, help_text='تصویر مرتبط با صفحه (سایز پیشنهادی: 1200x630 پیکسل)', null=True, upload_to='pages/featured_images/', verbose_name='تصویر شاخص')),
                ('image_alt', models.CharField(blank=True, help_text='توضیح مختصر درباره تصویر برای موتورهای جستجو', max_length=200, verbose_name='متن جایگزین تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'صفحه محتوایی',
                'verbose_name_plural': 'صفحات محتوایی',
                'ordering': ['navigation_order', 'title'],
                'indexes': [models.Index(fields=['slug', 'status'], name='page_conten_slug_7cca34_idx')],
            },
        ),
    ]
