# Generated by Django 5.2.4 on 2025-08-18 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='آدرس اصلی پست در صورت وجود محتوای تکراری', verbose_name='آدرس کانونیکال'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, help_text='توضیح مختصر درباره تصویر برای موتورهای جستجو و دسترسی\u200cپذیری', max_length=200, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='توضیح مختصر برای نمایش در نتایج جستجو (حداکثر 160 کاراکتر)', max_length=160, verbose_name='توضیحات متا'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='کلمات کلیدی مرتبط با پست (با کاما جدا شوند)', max_length=200, verbose_name='کلمات کلیدی متا'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='عنوانی که در نتایج جستجو نمایش داده می\u200cشود (حداکثر 60 کاراکتر)', max_length=60, verbose_name='عنوان متا'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='خلاصه کوتاه از محتوای پست (برای نمایش در صفحات لیست پست\u200cها)', verbose_name='چکیده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='تصویر اصلی مرتبط با پست (سایز پیشنهادی: 1200x630 پیکسل)', null=True, upload_to='blog/featured_images/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='تاریخ و زمان انتشار پست', null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'),
        ),
    ]
