"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fr1olbwvlb=1=x2p+!+juwjh8m!e5twzinh9m$f^bx!8p8hbsv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'hebrew-academy.ir',
    'hebrew.runflare.run'
]

CSRF_COOKIE_SECURE = True  # اگر از HTTPS استفاده می‌کنید
CSRF_COOKIE_HTTPONLY = True

# یا برای پذیرش همه زیردامنه‌ها:
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'https://*.hebrew-academy.ir',
    'https://hebrew-academy.ir',
    'http://hebrew-academy.ir',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_jalali',
    'django.contrib.humanize',
    'tinymce',
    'main',
    'account',
    'course',
    'blog',
    'comment',
    'page',
    'payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.site_settings',
                'main.context_processors.pages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'database/db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'UTC'

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/public/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "public","static")

MEDIA_URL = '/public/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "public","media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py - تنظیمات ساده‌تر
TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'width': '100%',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'silver',
    'language': 'fa',  # اگر زبان فارسی دارید
    
    # پلاگین‌های کاربردی
    'plugins': '''
        advlist autolink lists link image charmap print preview anchor
        searchreplace visualblocks code fullscreen table contextmenu
        insertdatetime media paste textcolor colorpicker hr pagebreak
        nonbreaking save autosave wordcount emoticons codesample
        directionality visualchars imagetools autoresize
    ''',
    
    # تولبار کامل
    'toolbar1': '''
        save | undo redo | bold italic underline strikethrough | 
        fontselect fontsizeselect | forecolor backcolor | 
        alignleft aligncenter alignright alignjustify | ltr rtl
    ''',
    'toolbar2': '''
        bullist numlist outdent indent | link unlink image media | 
        table | hr pagebreak nonbreaking | charmap emoticons | 
        visualblocks visualchars | searchreplace | fullscreen code preview
    ''',
    
    # تنظیمات کلی
    'menubar': 'file edit view insert format tools table help',
    'statusbar': True,
    'branding': False,  # حذف برند TinyMCE
    'elementpath': True,
    'resize': True,
    'autoresize_bottom_margin': 50,
    'autoresize_max_height': 500,
    'autoresize_min_height': 350,
    
    # تنظیمات آپلود تصویر
    'images_upload_url': '/tinymce/upload_image/',
    'automatic_uploads': True,
    'file_picker_types': 'image media',
    'images_reuse_filename': True,
    'images_upload_credentials': True,
    
    # تنظیمات تصاویر
    'image_advtab': True,
    'image_caption': True,
    'image_list': [],  # می‌توانید لیست تصاویر از پیش تعریف شده اضافه کنید
    'image_class_list': [
        {'title': 'تصویر کامل', 'value': 'img-fluid'},
        {'title': 'تصویر کوچک', 'value': 'img-thumbnail'},
        {'title': 'تصویر گرد', 'value': 'rounded'},
    ],
    
    # تنظیمات جدول
    'table_default_attributes': {
        'class': 'table table-bordered'
    },
    'table_default_styles': {},
    'table_class_list': [
        {'title': 'جدول ساده', 'value': 'table'},
        {'title': 'جدول با حاشیه', 'value': 'table table-bordered'},
        {'title': 'جدول راه راه', 'value': 'table table-striped'},
    ],
    
    # تنظیمات لینک
    'link_assume_external_targets': True,
    'link_list': [],  # می‌توانید لیست لینک‌های از پیش تعریف شده اضافه کنید
    'target_list': [
        {'title': 'همین پنجره', 'value': ''},
        {'title': 'پنجره جدید', 'value': '_blank'},
    ],
    
    # تنظیمات فونت
    'font_formats': '''
        Vazir=Vazir,Arial,sans-serif;
        Arial=arial,helvetica,sans-serif;
        Comic Sans MS=comic sans ms,sans-serif;
        Courier New=courier new,courier;
        Georgia=georgia,palatino;
        Helvetica=helvetica;
        Impact=impact,chicago;
        Symbol=symbol;
        Tahoma=tahoma,arial,helvetica,sans-serif;
        Terminal=terminal,monaco;
        Times New Roman=times new roman,times;
        Trebuchet MS=trebuchet ms,geneva;
        Verdana=verdana,geneva;
    ''',
    
    'fontsize_formats': '8pt 10pt 12pt 14pt 16pt 18pt 20pt 24pt 36pt 48pt',
    
    # تنظیمات راست به چپ
    'directionality': 'rtl',
    'content_css': '/static/css/tinymce-content.css',
    
    # تنظیمات ذخیره خودکار
    'autosave_ask_before_unload': True,
    'autosave_interval': '30s',
    'autosave_prefix': 'tinymce-autosave-{path}{query}-{id}-',
    'autosave_restore_when_empty': False,
    'autosave_retention': '2m',
    
    # تنظیمات paste
    'paste_data_images': True,
    'paste_as_text': False,
    'paste_auto_cleanup_on_paste': True,
    'paste_remove_styles': False,
    'paste_remove_styles_if_webkit': True,
    'paste_strip_class_attributes': 'all',
    
    # تنظیمات کد
    'codesample_languages': [
        {'text': 'HTML/XML', 'value': 'markup'},
        {'text': 'JavaScript', 'value': 'javascript'},
        {'text': 'CSS', 'value': 'css'},
        {'text': 'PHP', 'value': 'php'},
        {'text': 'Python', 'value': 'python'},
        {'text': 'Java', 'value': 'java'},
        {'text': 'C', 'value': 'c'},
        {'text': 'C++', 'value': 'cpp'},
        {'text': 'C#', 'value': 'csharp'},
        {'text': 'SQL', 'value': 'sql'},
    ],
    
    # فایل پیکر برای تصاویر
    'file_picker_callback': '''
        function (callback, value, meta) {
            if (meta.filetype === 'image') {
                var input = document.createElement('input');
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*');
                
                input.onchange = function () {
                    var file = this.files[0];
                    var reader = new FileReader();
                    
                    reader.onload = function () {
                        var id = 'blobid' + (new Date()).getTime();
                        var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                        var base64 = reader.result.split(',')[1];
                        var blobInfo = blobCache.create(id, file, base64);
                        blobCache.add(blobInfo);
                        callback(blobInfo.blobUri(), { title: file.name });
                    };
                    reader.readAsDataURL(file);
                };
                
                input.click();
            }
        }
    ''',
    
    # استایل‌های از پیش تعریف شده
    'style_formats': [
        {
            'title': 'تیتر اصلی', 'block': 'h1', 'styles': {
                'color': '#2c3e50',
                'font-weight': 'bold'
            }
        },
        {
            'title': 'تیتر فرعی', 'block': 'h2', 'styles': {
                'color': '#34495e',
                'font-weight': '600'
            }
        },
        {
            'title': 'پاراگراف مهم', 'block': 'p', 'classes': 'important-text',
            'styles': {'background-color': '#fff3cd', 'padding': '10px', 'border-right': '4px solid #ffc107'}
        },
        {
            'title': 'متن برجسته', 'inline': 'span', 'classes': 'highlight',
            'styles': {'background-color': '#ffeb3b', 'padding': '2px 4px'}
        },
        {
            'title': 'نقل قول', 'block': 'blockquote', 'classes': 'blockquote',
            'styles': {
                'border-right': '4px solid #007bff',
                'padding-right': '15px',
                'margin-right': '0',
                'font-style': 'italic',
                'background-color': '#f8f9fa'
            }
        }
    ],
    
    # فعال‌سازی کلیدهای میانبر
    'setup': '''
        function (editor) {
            // کلید میانبر برای ذخیره (Ctrl+S)
            editor.addShortcut('ctrl+s', 'Save', function() {
                var form = editor.getContainer().closest('form');
                if (form) {
                    form.submit();
                }
            });
            
            // کلید میانبر برای تمام صفحه (F11)
            editor.addShortcut('f11', 'Fullscreen', function() {
                editor.execCommand('mceFullScreen');
            });
        }
    ''',
}
    
  

TINYMCE_UPLOAD_PATH = 'tinymce_uploads/'
# اختیاری: تنظیم locale برای نمایش بهتر
USE_L10N = True
USE_TZ = True

# برای نمایش ارقام فارسی
JALALI_DATE_DEFAULTS = {
    'Strftime': {
        'date': '%Y/%m/%d',
        'datetime': '%Y/%m/%d - %H:%M:%S',
    },
    'Static': {
        'js': [
            # فایل‌های js در صورت نیاز
        ],
        'css': {
            'all': [
                # فایل‌های css در صورت نیاز  
            ]
        }
    }
}

SANDBOX = False

if SANDBOX:
    ZARINPAL_REQUEST_URL = "https://sandbox.zarinpal.com/pg/v4/payment/request.json"
    ZARINPAL_VERIFY_URL = "https://sandbox.zarinpal.com/pg/v4/payment/verify.json"
    ZARINPAL_STARTPAY = "https://sandbox.zarinpal.com/pg/StartPay/"
else:
    ZARINPAL_REQUEST_URL = "https://api.zarinpal.com/pg/v4/payment/request.json"
    ZARINPAL_VERIFY_URL = "https://api.zarinpal.com/pg/v4/payment/verify.json"
    ZARINPAL_STARTPAY = "https://www.zarinpal.com/pg/StartPay/"


ZARINPAL_MERCHANT_ID = "d3ee8bbe-233a-43ed-bdc5-bef89df810b2"
ZARINPAL_CALLBACK_URL = "https://hebrew-academy.ir/payment/verify/"
ZARINPAL_DESCRIPTION = "خرید از آکادمی عبری "
