# Generated by Django 5.2.4 on 2025-08-18 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('site_description', models.TextField(blank=True, verbose_name='توضحیات')),
                ('site_slogan', models.CharField(blank=True, max_length=200, verbose_name='شعار')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/', verbose_name='لوگو')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='settings/favicon/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png'])], verbose_name='آیکون')),
                ('footer_text', models.TextField(blank=True, verbose_name='متن فوتر')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='متن کپی رایت')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('contact_address', models.TextField(blank=True, verbose_name='آدرس')),
                ('eitaa_url', models.URLField(blank=True, verbose_name='آدرس ایتا')),
                ('rubika_url', models.URLField(blank=True, verbose_name='آدرس روبیکا')),
                ('meta_title', models.CharField(blank=True, help_text='پیشنهاد: بین ۵۰ الی ۶۰ کلمه', max_length=60, verbose_name='عنوان پایه سئو')),
                ('meta_description', models.TextField(blank=True, help_text='پیشنهاد: بین ۱۵- الی ۱۸۰ کلمه', verbose_name='توضیحات پایه سئو')),
                ('meta_keywords', models.CharField(blank=True, help_text='با - جدا کنید', max_length=200, verbose_name='کلمات کلیدی پایه سئو')),
                ('google_analytics_code', models.CharField(blank=True, max_length=50, verbose_name='کد گوگل آنالیتیکس')),
                ('google_tag_manager_code', models.CharField(blank=True, max_length=50, verbose_name='کد گوگل تگ')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='زمانی که فعال باشد، سایت از دسترس حارج می\u200cشود', verbose_name='حالت تعمیر')),
                ('custom_css', models.TextField(blank=True, verbose_name='Custom CSS')),
                ('custom_js', models.TextField(blank=True, verbose_name='Custom JavaScript')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروز شده در')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات های سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(help_text='سایز پیشنهادی: ۱۹۲۰ در ۱۰۸۰', upload_to='sliders/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک اسلاید')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('alt_text', models.CharField(blank=True, help_text='برای بهبود سئو', max_length=100, verbose_name='متن alt جایگزین')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
