# Generated by Django 5.2.4 on 2025-08-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blog_count',
            field=models.CharField(blank=True, max_length=20, verbose_name='تعداد مقاله  '),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='courses_count',
            field=models.CharField(blank=True, max_length=20, verbose_name='تعداد دوره آنلاین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_count',
            field=models.CharField(blank=True, max_length=20, verbose_name='تعداد ساعت آموزش '),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='students_count',
            field=models.CharField(blank=True, max_length=20, verbose_name='تعداد دانشجو'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
