# Generated by Django 5.2.4 on 2025-08-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesettings_blog_count_sitesettings_courses_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='special_texts',
            field=models.TextField(blank=True, help_text='جملات را با خط تیره (-) از هم جدا کنید. مثال: جمله اول-جمله دوم-جمله سوم', verbose_name='جملات خاص تایپ شونده'),
        ),
    ]
