# Generated by Django 5.2.4 on 2025-08-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesettings_special_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='لوگوی رسمی همکار را با فرمت مناسب (JPG, PNG) آپلود کنید', upload_to='partners/', verbose_name='لوگوی همکاران')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'همکار',
                'verbose_name_plural': 'همکاران',
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='special_texts',
            field=models.TextField(blank=True, help_text='جملات را با خط تیره (-) از هم جدا کنید. مثال: جمله اول-جمله دوم-جمله سوم و... - بدون ENTER', verbose_name='جملات خاص تایپ شونده'),
        ),
    ]
