# Generated by Django 5.2.4 on 2025-08-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partner_alter_sitesettings_special_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='با علامت کامای انگلیسی (,) جدا کنید', max_length=200, verbose_name='کلمات کلیدی پایه سئو'),
        ),
    ]
