# Generated by Django 5.2.4 on 2025-08-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sitesettings_meta_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='تصویر منبع را با فرمت مناسب (JPG, PNG) آپلود کنید', upload_to='sources/', verbose_name='تصویر منبع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'منبع/مرجع',
                'verbose_name_plural': 'منابع',
            },
        ),
    ]
