# Generated by Django 5.2.4 on 2025-08-31 06:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='landing_content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='محتوای لندینگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان لندینگ'),
        ),
    ]
